<?php
/**
 * WayTest
 *
 * PHP version 8.1
 *
 * @package  Voipex\Ipbx
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * IPBX API Documentation
 *
 * Access to all methods is granted through Bearer token.
 *
 * The version of the OpenAPI document: 1.98.2
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Voipex\Ipbx\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * WayTest Class Doc Comment
 *
 * @description call direction (Loc - local, In - incoming, Out - outgoing)
 * @package     Voipex\Ipbx
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WayTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Way"
     */
    public function testWay()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
