<?php
/**
 * Model1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Voipex\Ipbx
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IPBX API Documentation
 *
 * Access to all methods is granted through Bearer token.
 *
 * OpenAPI spec version: 1.98.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Voipex\Ipbx;

use PHPUnit\Framework\TestCase;

/**
 * Model1Test Class Doc Comment
 *
 * @category    Class
 * @description Model1
 * @package     Voipex\Ipbx
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Model1Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Model1"
     */
    public function testModel1()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "line"
     */
    public function testPropertyLine()
    {
    }

    /**
     * Test attribute "calldate"
     */
    public function testPropertyCalldate()
    {
    }

    /**
     * Test attribute "clid"
     */
    public function testPropertyClid()
    {
    }

    /**
     * Test attribute "src"
     */
    public function testPropertySrc()
    {
    }

    /**
     * Test attribute "dst"
     */
    public function testPropertyDst()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "billsec"
     */
    public function testPropertyBillsec()
    {
    }

    /**
     * Test attribute "disposition"
     */
    public function testPropertyDisposition()
    {
    }

    /**
     * Test attribute "accountcode"
     */
    public function testPropertyAccountcode()
    {
    }

    /**
     * Test attribute "userfield"
     */
    public function testPropertyUserfield()
    {
    }

    /**
     * Test attribute "filename"
     */
    public function testPropertyFilename()
    {
    }

    /**
     * Test attribute "way"
     */
    public function testPropertyWay()
    {
    }

    /**
     * Test attribute "trunk"
     */
    public function testPropertyTrunk()
    {
    }

    /**
     * Test attribute "hangupcause"
     */
    public function testPropertyHangupcause()
    {
    }

    /**
     * Test attribute "uniqueid"
     */
    public function testPropertyUniqueid()
    {
    }

    /**
     * Test attribute "linkedid"
     */
    public function testPropertyLinkedid()
    {
    }

    /**
     * Test attribute "organization"
     */
    public function testPropertyOrganization()
    {
    }

    /**
     * Test attribute "organization_person"
     */
    public function testPropertyOrganizationPerson()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "sipcallid"
     */
    public function testPropertySipcallid()
    {
    }

    /**
     * Test attribute "stamp"
     */
    public function testPropertyStamp()
    {
    }

    /**
     * Test attribute "cc_cb"
     */
    public function testPropertyCcCb()
    {
    }

    /**
     * Test attribute "queue"
     */
    public function testPropertyQueue()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {
    }

    /**
     * Test attribute "phone_number"
     */
    public function testPropertyPhoneNumber()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }

    /**
     * Test attribute "end_time"
     */
    public function testPropertyEndTime()
    {
    }

    /**
     * Test attribute "user_answered"
     */
    public function testPropertyUserAnswered()
    {
    }
}
