<?php
/**
 * ReportsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Voipex\Ipbx
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IPBX API Documentation
 *
 * Access to all methods is granted through Bearer token.
 *
 * OpenAPI spec version: 1.98.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Voipex\Ipbx;

use Voipex\Ipbx\Configuration;
use Voipex\Ipbx\ApiException;
use Voipex\Ipbx\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReportsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Voipex\Ipbx
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReportsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getReportsAgentsActivity
     *
     * Get agents activity.
     *
     */
    public function testGetReportsAgentsActivity()
    {
    }

    /**
     * Test case for getReportsAgentsActivitydurations
     *
     * Get agents activity durations.
     *
     */
    public function testGetReportsAgentsActivitydurations()
    {
    }

    /**
     * Test case for getReportsAgentsDailystats
     *
     * Daily agent statistics.
     *
     */
    public function testGetReportsAgentsDailystats()
    {
    }

    /**
     * Test case for getReportsCalls
     *
     * Returns extended calls information.
     *
     */
    public function testGetReportsCalls()
    {
    }

    /**
     * Test case for getReportsQueues
     *
     * Return statistics for queues.
     *
     */
    public function testGetReportsQueues()
    {
    }
}
